version: "3" 
services:
  web_titiatio:
    image: alexrogna/titiatio_web:prod
    expose:
      - 3000
    env_file:
      - .env/production/database_titiatio
      - .env/production/web_titiatio
    environment:
      - VIRTUAL_HOST=titiatio.alexrogna.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=titiatio.alexrogna.com
    networks:
      - proxy
    restart: always

  database_titiatio:
    image: postgres
    env_file:
      - .env/production/database_titiatio
    volumes:
      - db_data_titiatio:/var/lib/postgresql/data
    networks:
      - proxy
    restart: always
    
  db-migrator_titiatio:
    image: alexrogna/titiatio_web:prod
    command: ["./wait-for", "--timeout=300", "database_titiatio:5432", "--", "bin/rails", "db:create" , "db:migrate"]
    env_file:
      - .env/production/database_titiatio
      - .env/production/web_titiatio
    networks:
      - proxy
volumes:
  db_data_titiatio:
networks:
  proxy: